language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
  local_dir: _book/
  committer_from_gh: true
  
