--- 
title: "A Minimal Book Example"
author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Publishing Rbookdown with Github Pages and Travis

## Bookdown Guide

While we take the same approach as the [Bookdown guide](https://bookdown.org/yihui/bookdown/github.html), I update some steps to reflect changes with Travis.

First, as in the guide, set up gh-pages branch as noted in the guide:

```
# assume you have initialized the git repository,
# and are under the directory of the book repository now

# create a branch named gh-pages and clean up everything
git checkout --orphan gh-pages
git rm -rf .

# create a hidden file .nojekyll
touch .nojekyll
git add .nojekyll

git commit -m "Initial commit"
git push origin gh-pages
```

### Files to Modify/Add

#### .travis.yml
Depending on your file system, you may not see this file immediately because it starts with a period.
Look up on your system how to "view hidden files" if you wish to see it.

```
language: r
cache: packages
pandoc_version: 2.9.2.1

addons:
  apt:
    packages:
    - ghostscript

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
  local_dir: _book/
  committer_from_gh: true
```

#### _build.sh

You'll need to specify the commands to build your book in Travis:

```
#!/bin/sh

set -ev

Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
tlmgr option repository ctan
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

```


#### Description File
As noted on the Bookdown guide:

> The only thing in this file that really matters is the specification of dependencies. 
All dependencies will be installed via the devtools package.
If a dependency is on CRAN or BioConductor, you can simply list it in the Imports field of the DESCRIPTION file.
If it is on GitHub, you may use the Remotes field to list its repository name. 

So the takeaway is, list your RPackages used in `Imports`. Here's the example file:
```
Package: placeholder
Type: Book
Title: Does not matter.
Version: 0.0.1
Imports: bookdown, ggplot2
Remotes: rstudio/bookdown
```

### Travis
Let's do everything through the website to keep things simple and not using the terminal!

Create a Github PAT through the Github website and sign up for Travis CI.

You should see a list of your repositories and in your [profile](https://app.travis-ci.com/account/repositories), you should be sure to activate Github Apps integration.

When you find your repository in the dashboard, click it and in "More options>Settings" enter the Github PAT value into the Environmental Variables section. Name it `GITHUB_PAT` because that is what is specified in `.travis.yml`.

#### Note on Credit
We have limited free credits available on Travis CI. This means that we have probably around [1000 build minutes](https://github.com/matsim-org/matsim-libs/issues/1259) and the book make take around 10 minutes or even more to run. Ways to save time involve caching, through which we can add the following to our `.travis.yml` file:

```
sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
```
